practice-for-ch-rails-ninety-nine-cats2-long-practice-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except: :destroy do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users

  resource :session, only: [:new, :create, :destroy]

end

practice-for-ch-rails-ninety-nine-cats2-long-practice-main/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  # validates :username, :session_token, presence: true, uniqueness: true
  # validates :password_digest, presence: true
  # validates :password, length: { minimum: 6 }, allow: nil
  # validates :password, inclusion: { in: ["!", "@", ".", "?"] }

  # before_validations :ensure_session_token

  attr_reader :password

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    bcrypt_obj = BCrypt::Password.new(self.password)
    bcrypt_obj.is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  private

  def generate_unique_session_token
    token = SecureRandom::urlsafe_64
    while User.exists?(session_token: token)
      token = SecureRandom::urlsafe_64
    end
    token
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end
end

practice-for-ch-rails-ninety-nine-cats2-long-practice-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])

    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url
    else
      @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])

    render :edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_url
    else
      @user.errors.full_messages
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

practice-for-ch-rails-ninety-nine-cats2-long-practice-main/app/helpers/users_helper.rb
module UsersHelper
end

practice-for-ch-rails-ninety-nine-cats2-long-practice-main/app/views/users/edit.html.erb
<form action="<%= users_url %>" method = "PATCH">

    <label for= "username"> Username:
        <input type="text" id="username" name="user[username]" value="<%= @user.username %>">
        </label>
        <br/>

    <label for="password">Password:
        <input type="password" id="password" name="user[password]" value="">
        </label>
        <br/>

    <input type="submit" value="Create User">


</form>

practice-for-ch-rails-ninety-nine-cats2-long-practice-main/app/views/users/index.html.erb
<div class="sub-header">
  <h2>Hey, this is Users Index</h2>
</div>

<div class="item link">
  <a href="<%= new_user_url %>">Add New User</a>
</div>

<ul class="list">
  <% @users.each do |user| %>
    <li>
      <a href="<%= user_url(user) %>">
        <%= render "user", user: user %>
      </a>
    </li>
  <% end %>
</ul>

practice-for-ch-rails-ninety-nine-cats2-long-practice-main/app/views/users/new.html.erb
<form action="<%= users_url %>" method = "POST">

    <label for= "username"> Username:
        <input type="text" id="username" name="user[username]" value="<%= @user.username %>">
        </label>
        <br/>

    <label for="password">Password:
        <input type="password" id="password" name="user[password]" value="">
        </label>
        <br/>

    <input type="submit" value="Create User">


</form>